AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.1
  SuggestExtensions: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/graphql_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'config/application.rb'
    - 'app/graphql/types/query_type.rb'

Naming/FileName:
  Exclude:
    - 'config/initializers/rswag-ui.rb'
